---
name: Util-Properties
version: 0.12
author:
  - 'Alexandre Masselot <alexandre.masselot@genebio.com>'
abstract: Java.util.properties like class
license: lgpl
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Digest::MD5::File: 0
  IO::All: 0
  LockFile::Simple: 0
  Object::InsideOut: 0
provides:
  Util::Properties:
    file: lib/Util/Properties.pm
    version: 0.12
  Util::Properties::Combine:
    file: lib/Util/Properties/Combine.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
