--- #YAML:1.0
name: Util-Properties
version: 0.03
author:
  - |-
    Alexandre Masselot <alexandre.masselot@genebio.com>
abstract: Java.util.properties like class
license: gpl
requires:
  Class::Std: 0
  Digest::MD5::File: 0
  IO::All: 0
  LockFile::Simple: 0
  Test::More: 0
provides:
  Util::Properties:
    file: lib/Util/Properties.pm
    version: 0.03
generated_by: Module::Build version 0.24
